sudo: required
services:
  - docker
env:
  global:
    - OWNER=SAMET
before_install:
  - echo "[BEFORE INSTALL]"

script:
  - echo "[SCRIPT]" 

after_success:
  - echo "[AFTER INSTALL]"
  - docker build . -t sametma/dotnet
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push sametma/dotnet

